{{ 
    config(
            materialized="table", 
            schema='marts'
) 
}}
select
    sk_connector_key,
    charging_station_id,
    station_name,
    operator_name,
    owner_name,
    station_address,
    is_24_hours_flag,
    car_park_count,
    has_carpark_cost_flag,
    max_time_limit,
    has_tourist_attraction_flag,
    latitude,
    longitude,
    date_first_operational,
    station_status,
    has_charging_cost_flag,
    connector_type,
    connector_power,
    connector_stand,
    connector_status,
    connector_count,
    dbt_valid_from,
    dbt_valid_to,
    dbt_updated_at
from 
    {{ ref('ev_charging_stations_connectors_snapshot') }}